# Generated by Django 5.2.6 on 2025-09-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='alert_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
