# Generated by Django 5.2.6 on 2025-09-16 01:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.DecimalField(decimal_places=2, help_text='Valor percentual entre 0 e 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ram_usage', models.DecimalField(decimal_places=2, help_text='Valor percentual entre 0 e 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hd_space_remaining', models.DecimalField(decimal_places=2, help_text='Valor percentual entre 0 e 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('latency', models.FloatField(blank=True, help_text='Latência em milisegundos.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_connected', models.BooleanField(default=False, help_text='Indica se o dispositivo tem conexão com o DNS 8.8.8.8 (True=1, False=0).')),
                ('boot_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp em UTC+00 do momento em que o dispositivo foi ligado.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetries', to='device.device', to_field='uuid')),
            ],
            options={
                'verbose_name': 'Telemetria',
                'verbose_name_plural': 'Telemetrias',
            },
        ),
    ]
