# Generated by Django 5.2.6 on 2025-09-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_telemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='sn',
            field=models.CharField(editable=False, max_length=12, unique=True, verbose_name='Número de série'),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='hd_space_remaining',
            field=models.DecimalField(decimal_places=2, help_text='Valor em GB.', max_digits=5),
        ),
    ]
