# Generated by Django 5.2.6 on 2025-09-22 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_telemetry_created_at_telemetry_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('cpu_usage', 'CPU Usage'), ('ram_usage', 'RAM Usage'), ('temperature', 'Temperature'), ('latency', 'Latency')], max_length=50)),
                ('comparison', models.CharField(choices=[('gt', '>'), ('lt', '<'), ('eq', '==')], max_length=2)),
                ('threshold', models.FloatField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devices', models.ManyToManyField(blank=True, to='device.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
