# Generated by Django 5.2.6 on 2025-09-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_notificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
