# Generated by Django 5.2.6 on 2025-09-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_notificationconfig_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationConfig',
        ),
    ]
